version: '3'

services:
    server:
        build:
            context: .
            dockerfile: Dockerfile.dev
        command: ./manage.py runserver 0.0.0.0:8001
        ports:
            - '8001:8001'
        volumes:
            - ./sts:/usr/src/app
        depends_on:
            - db
        networks:
            - backend
        environment:
            - DEBUG=1
            - BUILD_ENV=local
            - ALLOWED_HOSTS=
            - 'SECRET_KEY=KuTGnNBVe5UIijY&%tgv456ujmKJG'
            - DATABASE_HOST=db
            - DATABASE_USER=stsuser
            - DATABASE_PASSWORD=stsuser-pass
            - DATABASE_NAME=sts
            - DATABASE_PORT=5432

    db:
        image: postgres
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - backend
        environment:
            - POSTGRES_USER=stsuser
            - POSTGRES_PASSWORD=stsuser-pass
            - POSTGRES_DB=sts

    db-admin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: farsanbf@yahoo.com
            PGADMIN_DEFAULT_PASSWORD: stsadmin
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        depends_on:
            - db
        ports:
            - '8080:80'
        networks:
            - backend

networks:
    backend:
        driver: bridge

volumes:
    postgres-data:
    pgadmin-data:

