version: '3.7'

services:
    server:
        build: .
        command: gunicorn sts.wsgi:application --bind 0.0.0.0:8000
        env_file: ./.env.prod
        expose:
            - 8000
        depends_on:
            - db
        volumes:
            - static_volume:/usr/src/app/static
            - media_volume:/usr/src/app/media

    db:
        image: postgres
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - ./.env.prod.db

    nginx:
        build: ./nginx
        ports:
            - '1337:80'
        depends_on:
            - server
        volumes:
            - static_volume:/usr/src/app/static
            - media_volume:/usr/src/app/media

volumes:
    postgres_data: 
    static_volume:
    media_volume:
