FROM python:3

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update && \
        apt-get install -y postgresql-client-common

WORKDIR /usr/src/app

COPY ./sts/requirements.txt /usr/src/app
RUN pip install -r requirements.txt

COPY ./sts/entrypoint.sh /usr/src/app/

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
EXPOSE 8081

COPY ./sts/ /usr/src/app
RUN chmod a+x /usr/src/app/entrypoint.sh
