name: Docker Image CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image for server
      run: |
        docker build . -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/sts-website_server:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/sts-website_server:latest
    - name: Build the Docker image for nginx
      run: |
        docker build ./nginx/ -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/sts-website_nginx:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/sts-website_nginx:latest
